apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{.Values.backnetpol}}"
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: "{{.Values.backend.name}}"
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: "{{.Values.frontend.name}}"
      ports:
        - protocol: TCP
          port: 8080
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: "{{.Values.db.name}}"
      ports:
        - protocol: TCP
          port: 27017
