apiVersion: v1
kind: Service
metadata:
  name: "{{.Values.db.svc}}"
  labels:
    app: "{{.Values.db.svc}}"
spec:
  type: ClusterIP
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: "{{.Values.db.name}}"
