apiVersion: v1
kind: Service
metadata:
  labels:
    app: "{{.Values.frontend.name}}"
  name: "{{.Values.frontend.svc}}"
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      nodePort: 30000
      protocol: TCP
      targetPort: 3000
  selector:
    app: "{{.Values.frontend.name}}"
status:
  loadBalancer: {}
