apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{.Values.netpol }}"
spec:
  podSelector:
    matchLabels:
      app: "{{.Values.db}}"
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: "{{.Values.deploy1.name }}"
        - podSelector:
            matchLabels:
              app: "{{.Values.deploy2.name}}"
      ports:
        - protocol: TCP
          port: 27017
