apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{.Values.pv.name}}"
spec:
  capacity:
    storage: "{{.Values.pv.storage}}"
  volumeMode: Filesystem
  accessModes:
    - "{{.Values.pv.accessMode}}"
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /data
